server:
  port: 8080
  servlet:
    context-path: /spring

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/my_first_spring_boot"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: "6NqVPYaDts2sDIiI7dPviiFW5Nk/48YOO4iuABfIqUHmfQdP1yz0dX6AP8M9DPIb"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second